travis:
  secure:
    BINSTAR_TOKEN: DZYt8rn0MEIxokbTm9a4yLPzKsrPaqqvL5PZmMuPal2FzxUL5JljQZh+gTPMO6CABhKF3qwp88iodnCj4/7yHK8d4dkWAsAdDsWd5LhF11ggluISvY0cHC4TV2Olxz2v7eWzBULEPUxKLf8Y6Qr+HkwZtCkWCj9k/yUeLmHnnmWVi66cbMdDqKncSEFb4H4dwZHSI0Ev662I3fzd3Xjj0f5EZ/AW0dzZfPGjoapVIGsQ4bf58Uvr3O2Qx+zasg/oT5yKx6SiMNvP3QYYJwErcjkv3vD1oh3hpRGDcpO6fUWqXoCnMcMimTk+yzZLGBnorgWdbOQ1ety/MDsdxwSPQUk4FgeRm8+l8gJG8VgJdLxoJu+TUnzjEUEE29829ewdQSaidiAmLKbaic4/Agfi+PBftZPcf62tI2osQnIZEKWZrdfUTrgPNS3OsqJZa0Wo0yqDWv/8WM6ACJZmyV0lSXG48b3AZwQBJbUUF0gDeeJ/oLtFPfjMuwFhhARVICP25wa4ufqgLfQi6zo/r+VJnn56WnpB2E36lGVNvWFzSOOE1lcoBLm0d0tx3UGyqPPO4EDqW5PJ8LM1hYXVUV36hW6P5pMauAZD+SSb1ubx6j9GiLIUs55pnrOdQ31WLknULVLbjU2bOHdAM8jZpkIPsImmENp7O4crm7BmvjLpgzY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
