travis:
  secure:
    BINSTAR_TOKEN: FvY9/oMF35Jjg1XiTRCxDh+eNbDbEgcl2Ef9nXkQ7XF/MIFJCNd30eNFrwYA6Y8Fmb202MRhSPJwJ3YX5qfcl9y7m9J46m9z9NnpPnHFpEgD4rIiAVqThJOhiGeBgFhcikPS4wk0b9DCAVxEw/WMUL55tO4PU3ijd8d9vHGqVAxZt5kHRswNUKyZD6xNfe1HRC3jX9T/NQIbDKM7iLYEsGtnNqBaTbvzAG0m8fpeQfT7lzNMKhK3rn8febOhlmGFA2nf/wFa391OWpcegWZ1mZrqp/5wQ1zFDIucPJmSSpGGOdbB0VXNl+IZfLDAEgF/+S+T2hqGDeiP3zAMUTTHE4E2Th/jtGklltL7/Rd9ck9BruMrPuuAt78tseNWq4bWn6sXew+O6gbFSM97OFphOhuq3GPRGbKR9Mr94EpS0CLFPZc/QN+fGZjjt8L0XKrMJc2nvczhzVKAzzWeVGCaqrjnvFOV0uE9d5sb+6yNkTt4W/h7n6ANOClnGJ0cyd38mtb0rWVw57NPeixPVQrl7Car64iQcuNGYqAwR5f7XsxIhHMC0wqikwQ0N+0k1/YXbatFNvIp3dGVrTNquYYBgSDlJpcenxPZPq1iQYV8qRVGcZVTsnm/KCPaRwm7WY3fHPOmYD3W6XO8SPFw7RK4jMdyCYgeUs6nbFQCSh7PWLo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
